name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14, 1.15]

    name: Golang ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go: { { matrix.go } }
      - run: go test -v ./...
      - run: go run math.go
